import ts from 'typescript';
import fs from 'node:fs';
import path from 'node:path';
const texts = new Set([
  'Preferred language',
  'Welcome back',
  'Sign in',
  'Create account',
  'Please complete all required fields with valid values.',
  'Remove this member and their account from this group?',
  'Zoom in',
  'Zoom out',
  'Active meeting point',
]);
function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!['locales', 'localization', 'i18n'].includes(entry.name)) walk(file);
      continue;
    }
    if (
      !/\.tsx?$/.test(file) ||
      ['languages.ts', 'localeOptions.ts', 'LanguageProvider.tsx', 'localization.ts'].includes(
        entry.name,
      )
    )
      continue;
    const source = ts.createSourceFile(
      file,
      fs.readFileSync(file, 'utf8'),
      ts.ScriptTarget.Latest,
      true,
      file.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
    );
    function visit(n) {
      if (ts.isStringLiteral(n) || ts.isNoSubstitutionTemplateLiteral(n) || ts.isJsxText(n)) {
        const value = n.text.replace(/\s+/g, ' ').trim();
        if (value && /[A-Za-z]/.test(value) && value.length <= 12000) texts.add(value);
      }
      ts.forEachChild(n, visit);
    }
    visit(source);
  }
}
walk('frontend/src');
walk('backend/src');
walk('shared');
fs.mkdirSync('shared/localization', { recursive: true });
fs.writeFileSync(
  'shared/localization/catalog.ts',
  '// Generated by scripts/catalog.mjs. Public source strings only; never user content.\nexport const UI_CATALOG: readonly string[] = ' +
    JSON.stringify([...texts].sort(), null, 2) +
    ';\n',
);
console.log('Indexed ' + texts.size + ' source strings.');
